import connectMongo from "@/middleware/mongoose";
import profileModel from "@/models/profileModel";
import { Inter } from "@next/font/google";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useRef, useState } from "react";
import { BsCamera } from "react-icons/bs";
import { HiOutlineDotsHorizontal } from "react-icons/hi";

const inter = Inter({ subsets: ["latin"] });

function Gallery({ mydata }) {
  const [avatar, setAvatar] = useState({});
  const [image, setImage] = useState(null);
  const [progress, setProgress] = useState(0);
  const fileInputRef = useRef(null);
  const router = useRouter();

  const handleUpload = async () => {
    const config = {
      onUploadProgress: function (progressEvent) {
        var percentCompleted = Math.round(
          (progressEvent.loaded * 100) / progressEvent.total
        );
        setProgress(percentCompleted);
      },
    };
    let formData = new FormData();
    formData.append("avatar", avatar);

    const { data } = await axios.post("api/upload", formData, config);
    setProgress(0);
    fileInputRef.current.value = "";
    setAvatar({});
    setImage(null);
    router.reload(window.location.pathname);
  };

  const handleDot = (id) => {
    const deleteBtn = document.getElementById(id);
    deleteBtn.classList.toggle("hidden");
  };
  const handleDelete = async (id) => {
    const { data } = await axios.get(`/api/photo/${id}`);
    console.log(data);
    router.reload(window.location.pathname);
  };
  return (
    <>
      <Head>
        <title>Photo upload</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div
            style={{ width: progress + "%", background: "red", height: 10 }}
          ></div>
          <div className="relative w-[16rem] mx-auto">
            <Image
              className="rounded-md object-cover h-[160px]"
              width={250}
              height={250}
              src={image || "/background.jpg"}
              alt="s"
            />

            <div>
              <p className="overflow-hidden">{avatar?.name}</p>
              <button
                className="bg-orange-400 rounded-md px-3 py-1 block w-fit ml-auto"
                onClick={handleUpload}
              >
                upload
              </button>
            </div>
            <BsCamera
              onClick={() => fileInputRef.current.click()}
              className="absolute top-2 right-3 text-2xl cursor-pointer"
            />
          </div>
          <input
            className="hidden"
            ref={fileInputRef}
            type="file"
            onChange={(e) => {
              setAvatar(e.target.files[0]);
              setImage(URL.createObjectURL(e.target.files[0]));
            }}
          />
        </div>
        <div className="grid grid-cols-[2fr_4fr_2fr_4fr] gap-3 mt-8 w-4/5 mx-auto">
          {mydata.reverse().map((photo) => (
            <div className="relative" key={photo._id}>
              <div className="absolute right-2">
                <HiOutlineDotsHorizontal
                  className="cursor-pointer ml-auto "
                  onClick={() => handleDot(photo._id)}
                />
                <div
                  id={photo._id}
                  onClick={() => handleDelete(photo._id)}
                  className="bg-white py-2 px-3 rounded-md cursor-pointer hidden"
                >
                  delete
                </div>
              </div>

              <Image
                alt="gallery"
                className="w-full object-cover rounded-md h-[180px]  block"
                width={100}
                height={100}
                src={photo.avatar}
              />
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  connectMongo();
  const Apidata = await profileModel.find();
  return {
    props: { mydata: JSON.parse(JSON.stringify(Apidata)) }, // will be passed to the page component as props
  };
}
export default Gallery;
